"""empty message

Revision ID: 2ded0108616d
Revises: 0254a82a6f2f
Create Date: 2022-05-03 23:52:51.562172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ded0108616d'
down_revision = '0254a82a6f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_answer_voter_question_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_answer_id_answer'), 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_answer_id_answer'), type_='foreignkey')
        batch_op.create_foreign_key('fk_answer_voter_question_id_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###
